cd /home/ubuntu/covid/data/update
sudo /home/ubuntu/miniconda3/bin/python3.8 ../GT_region.py
sudo /home/ubuntu/miniconda3/bin/python3.8 ../Get_Google_trend_all.py
sudo docker exec -it covid_webapp_1 Rscript /srv/data/update/download_data.R
sudo cp StateGeo.csv ../us
sudo cp GT_data_combined.csv ../us
sudo cp US_mobility.csv ../us
sudo cp all-states-history.csv ../us
sudo cp COVID_Tracking_US.csv ../us
